/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Платформа подбора роботизированных решений API
 * Контракт API авторизации платформы.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Дополнительные данные об ошибке, если они нужны клиенту.
 */
export type ErrorResponseDetails = { [key: string]: unknown };
