/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Платформа подбора роботизированных решений API
 * Контракт API авторизации платформы.
 * OpenAPI spec version: 0.1.0
 */

export interface LoginRequest {
  /** @maxLength 254 */
  email: string;
  password: string;
}
