/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Платформа подбора роботизированных решений API
 * Контракт API авторизации платформы.
 * OpenAPI spec version: 0.1.0
 */
import type { ErrorResponse } from './error-response';

/**
 * Превышен лимит запросов.
 */
export type RateLimitedResponse = ErrorResponse;
