/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Платформа подбора роботизированных решений API
 * Контракт API авторизации платформы.
 * OpenAPI spec version: 0.1.0
 */

export interface RegisterRequest {
  /**
     * Email. Сервер удаляет крайние пробелы и каноникализирует адрес перед проверкой уникальности.
     * @maxLength 254
     */
  email: string;
  /**
     * Имя без управляющих символов. Сервер удаляет крайние пробелы.
     * @minLength 1
     * @maxLength 100
     */
  firstName: string;
  /**
     * Фамилия без управляющих символов. Сервер удаляет крайние пробелы.
     * @minLength 1
     * @maxLength 100
     */
  lastName: string;
  /**
     * Пароль длиной от 12 до 128 символов.
     * @minLength 12
     * @maxLength 128
     */
  password: string;
}
