// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    token_hash,
    user_id,
    created_at,
    last_seen_at,
    idle_expires_at,
    absolute_expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	TokenHash         []byte             `json:"token_hash"`
	UserID            string             `json:"user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, first_name, last_name, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, first_name, last_name, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT
    s.token_hash,
    s.created_at AS session_created_at,
    s.last_seen_at,
    s.idle_expires_at,
    s.absolute_expires_at,
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    u.password_hash,
    u.role,
    u.created_at AS user_created_at,
    u.updated_at AS user_updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionUserRow struct {
	TokenHash         []byte             `json:"token_hash"`
	SessionCreatedAt  pgtype.Timestamptz `json:"session_created_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt     pgtype.Timestamptz `json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	ID                string             `json:"id"`
	Email             string             `json:"email"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	PasswordHash      string             `json:"password_hash"`
	Role              string             `json:"role"`
	UserCreatedAt     pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt     pgtype.Timestamptz `json:"user_updated_at"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.TokenHash,
		&i.SessionCreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, password_hash, role, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_seen_at = $2, idle_expires_at = $3
WHERE token_hash = $1
  AND idle_expires_at > $2
  AND absolute_expires_at > $2
`

type TouchSessionParams struct {
	TokenHash     []byte             `json:"token_hash"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	IdleExpiresAt pgtype.Timestamptz `json:"idle_expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.TokenHash, arg.LastSeenAt, arg.IdleExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
